# 参考: https://github.com/golang/dep/blob/master/cmd/dep/ensure.go
required = []
noverify = ["golang.org/x/sys", "golang.org/x/crypto"]

[[override]]
  name = "golang.org/x/sys"
  branch = "master"
  source = "https://github.com/golang/sys.git"

[[override]]
  name = "golang.org/x/net"
  branch = "master"
  source = "https://github.com/golang/net.git"

[[override]]
  name = "github.com/gin-gonic/gin"
  version = "v1.3.0"
  source = "https://github.com/gin-gonic/gin"

[[override]]
  name = "github.com/jinzhu/gorm"
  version = "v1.9.2"
  source = "https://github.com/jinzhu/gorm"

[[override]]
  name = "github.com/golang/protobuf"
  version = "v1.2.0"
  source = "github.com/golang/protobuf"

[[override]]
  name = "github.com/yuwenhui/gopkg"
  branch = "master"
  source = "github.com/yuwenhui/gopkg.git"


